

import React, { ReactNode } from "react";



interface AdminLayoutProps {
  children: ReactNode;

}
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<AdminLayoutProps> = ({ children }) => {
  return (
    <section className="grid grid-cols-7 w-full h-full">
     <section className="col-span-1 w-full h-full bg-blue-400 py-4 space-y-2">
      <button className="w-full hover:bg-blue-200 h-12 border-b border-t flex items-center justify-start px-5 font-bold text-lg">
        Catatan
      </button>
      <button className="w-full h-12 border-b border-t">
        Catatan
      </button>
     </section>
     <section className="col-span-6 p-5">{children}</section>
    </section>
  );
};

export default RootLayout;
