import "./globals.css";

import React, { ReactNode } from "react";
import { Inter } from "next/font/google";
import ReactQuery from "@/component/ReactQuery";
import CustomChakra from "@/component/CustomChakra";
import NextAuthProvider from "@/component/NextAuthProvider";
import { Session } from "next-auth";
import Nav from "./nav";
import 'react-responsive-datepicker/dist/index.css'

const inter = Inter({ subsets: ["latin"] });

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<NextAuthProps> = ({ children, session }) => {
  
  return (
    <html lang="en">
      <body>
        <NextAuthProvider session={session}>
          <ReactQuery>
            <CustomChakra>
              <section className="h-screen w-screen">
                <section className="h-[100px]">
                  <Nav></Nav>
                </section>
                <section className="h-[calc(100%-100px)] w-full">
                  {children}
                </section>
              </section>
            </CustomChakra>
          </ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
